Add getTasksWithManagerId
satheeshkumarvadivel/TaskTracker pull request #6
Opened 2022-10-20 07:39 UTC by anshpand

2022-10-20 08:25 UTC, saitejaboggarapu approved these changes

2022-10-20 08:34 UTC, satheeshkumarvadivel requested changes

2022-10-20 08:34 UTC, satheeshkumarvadivel commented on build.gradle
> +	implementation group: 'org.json', name: 'json', version: '20220924'
Do we need to use this? Can we do it with java classes instead?

2022-10-20 08:34 UTC, satheeshkumarvadivel commented on src/main/java/com/example/demo/rest/TaskResource.java
> +    @GetMapping("/managerId")
Can we change this to "/api/v1/users/{userId}/teamtasks" and get the managerId from the provided userId?
Extract to a different Resource class if needed.

2022-10-20 08:34 UTC, satheeshkumarvadivel commented on src/main/java/com/example/demo/rest/TaskResource.java
> +            JSONObject task = new JSONObject();
Let's use java classes instead of JSONObject

2022-11-07 06:35 UTC, satheeshkumarvadivel approved these changes
Looks good

2022-11-07 06:35 UTC, merged